import Header from "@component/components/organisms/header";
import "../styles/globals.css";
import LayoutWrapper from "./layoutWrapper";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <LayoutWrapper>
          <Header />
          {children}
        </LayoutWrapper>
      </body>
    </html>
  );
}
