"use client";
import Header from "@component/components/organisms/header";
import "../styles/globals.css";
import LayoutWrapper from "./layoutWrapper";
import { useRouter } from "next/navigation";
import BackBtn from "@component/components/atoms/back-btn";
import { store } from "@component/store";
import { Provider } from "react-redux";
import AuthProvider from "@component/providers/AuthProvider";
import { useAppSelector } from "@component/helpers/ReduxHooks";
// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <AuthProvider>
            <LayoutWrapper>
              <Header />
              {children}
            </LayoutWrapper>
          </AuthProvider>
        </Provider>
      </body>
    </html>
  );
}
